### ISSUE TITLE
Gui respawn button does not count down properly.

### ISSUE THREAD

**Issue by dffdff2423** [cosmatic-drift-14/cosmatic-drift#133]
## Description

The respawn button is not synchronized with the respawn timer, instead it counts down from some unknown point. The `ghostrespawn` command works as expected.

**Reproduction**

- deadmin (not sure if needed)
- Join round
- Wait a minute or so
- Jump into cryo pod
- /ghost
- Respawn timer should be lower than expected, but the ghostrespawn command reports the correct time remaining and does not let you respawn when the time on the gui runs out.

**Comment by LankLTE** [comment]
I'm aware of this, but have no good idea how to fix it. The ghostrespawn command and the button both use the same thing to track their time, but for some reason the button just never shows the correct time.
