### ISSUE TITLE
[RFC/Design Doc] Smuggler "antag"

### ISSUE THREAD

**Issue by dffdff2423** [cosmatic-drift-14/cosmatic-drift#142]
## Description

The smuggler would be an antagonist that is the "opposite" of the thief. Instead of trying to steal items from the station, their job would be to provide illegal or hard to acquire items for the crew.  The smuggler would have a method of acquiring items for currency that is more complex than teleporting it into their inventory. Preferably, it should involve interacting with other people in some way. I think it would be best for the currency to just be normal specos and perhaps telecrystals as a secondary currency for more advanced items. Using normal specos for currency allows for more drama because they can be acquired though robbery. The smuggler should start with some amount of currency and would gain more upon the buyer's use of the item. This should be interpreted as the buyer wireing money to them from an off-station account, perhaps with a popup asking the player if they would like/are able to pay. 

### Objectives

The smuggler would get two objectives:
- Provide your services to the crew
   - This would greentext upon gaining funds from a successful transaction.
- Escape to CentCom alive and unrestrained, without your business being discovered.
   - This would work like the standard escape to CC, but with the possibility for both admins and the player to mark it as failed.
   
### Legality of Smuggling

The act of selling things to the stations crew should not be considered illegal unless they goods being sold are illegal. However, what they are doing is not exactly liked by NT.

### Available Goods

This is just a short list of goods that could be potentially available. I think it could be interesting to have some goods that can only be acquired by smugglers (eg. exotic drugs). 

- Drugs
   - Bliss
   - Deso
   - Ephidrine
   - Nocturine
   - Etc.....
- Arms
   - Modular receivers
   - Light guns
   - Combat Knives
- Syndicate Clothes
- Plushies
- Misc. comfort items

## Unresolved Questions
- Should security and command be eligible to be a smuggler?
   - It has been suggested that Captain, HoS, and Warden be ineligible simply because their armory access would be too powerful but that other than that, security and command would be eligible.  However, this point is likely moot with the decision to make smugglers ahelp only.
- Playtime
   - This would be up to the admins, but I would guess it should be comparable to captain.
 - Frequency of occurrence.
   - My understanding is that antags should not be an every round occurrence. Should they be spawn able though random chance? Or ahelp only?
   - The consensus seems to be to make it ahelp only until we start having rounds that admins don't actively watch.

**Comment by OctoRocket** [comment]
There is the problem that most people don't have access to spesos, so most of the time I'd have to imagine that only cargo will being purchasing items.

**Comment by dffdff2423** [comment]
The idea would be that people are wiring cash though an "off station" back account because NT does not permit people to carry cash during the shift.

**Comment by dffdff2423** [comment]
I don't think this is a good fit for CD in it's current state.
