### ISSUE TITLE
Traits menu is a mess

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [cosmatic-drift-14/cosmatic-drift#240]
## Description

CD currently has a *lot* of traits, and it would be much nicer if we could have something similar to /tg/'s quirk menu, where you can drag it and have a neat little icon and the description is shown right there.

![image](https://github.com/cosmatic-drift-14/cosmatic-drift/assets/67359748/9ffe98ab-507c-4c96-ba28-e72ea990cdc5)

**Additional context**

This is on my to-do list of things I wanna do for fun, I'm just leaving it here for triage purposes

**Comment by dffdff2423** [comment]
It might be better to PR that upstream rather than here. I don't see any reason why upstream would not want an improved traits UI.

**Comment by dffdff2423** [comment]
Given that wizden has overhauled the traits menu a bit ago I am going to close this.
