### ISSUE TITLE
The tail wagging emote should be disabled if the tail marking does not support it.

### ISSUE THREAD

**Issue by dffdff2423** [cosmatic-drift-14/cosmatic-drift#260]
Not all tails have functioning wagging. If this is the case we should disable the wag tale emote button.

**Comment by dffdff2423** [comment]
Fixed in https://github.com/cosmatic-drift-14/cosmatic-drift/pull/261

**Comment by dffdff2423** [comment]
I have no clue why I closed this. It is still an issue. I also need to check if it is also an issue upstream.

**Comment by LankLTE** [comment]
Closing this as it’s an issue upstream.
