### ISSUE TITLE
[Feature Request/Idea Discussion] Antithesis Necrosis Casket (The ANC)/Increasing Time To Rot

### ISSUE THREAD

**Issue by PursuitInAshes** [cosmatic-drift-14/cosmatic-drift#3]
### Description
There was some discussion in the discord about increasing the rot time due to the length rounds are planned to be. Then the discussion thanks to Nairrod shifted to what a machine that reverses the rot status effect would look like. I decided to move it to a github issues to keep the discussion more organized and to not lose the idea.

Nairrod came up with the name found [here](https://github.com/cosmatic-drift-14/cosmatic-drift/issues/3#issuecomment-1783408087)

**Idea Breakdown**
The intent is a machine that takes a while to revert the decomposition of a body, through use of a chemical (Probably a new one? Epi could work aswell if we don't want to add another chemical for chemists to make).

Insert body into machine -> Insert chemical -> Turn on machine -> "x" amount of time later, the body is no longer decomposed and can be revived normally.

**Balancing**
This should probably take a while, probably five or more minuets, maybe even longer?
This should still cause memory loss for the shift most likely, the IC reasoning could be the process doesn't entirely protect the brain, or the brain damage from rotting is to severe to preserve the recent (shift) memories.
This should probably be a Tier two or three science tech, I'm thinking three because it does out right bring people back into the shift.
The further rotted a body is rotted, it should take damage per unit of rot removed. Probably lacerations and heat. The more rotted the body is, the more damage will have to be healed after the machine is done. [Idea was put here.](https://github.com/cosmatic-drift-14/cosmatic-drift/issues/3#issuecomment-1783408087)

**Implimation/Other Notes**
Besides spriting and the actual code work, we should probably include a guidebook entry for this.

**Comment by Nairodian** [comment]
Tossing on the concept of the body being damaged during the process, so the more it's rotted the more damage you'll have to heal later, probably a mix of lacerations and heat.

Also name it something stupidly direct but fancy sounding, only idea that comes to mind right now for me is, "Antithesis Necrosis Casket"

**Comment by Nairodian** [comment]
ANC sounds pretty good actually, heh. Yeah I like that for a name. "Denecrosis" just doesn't sound proper.

**Comment by LankLTE** [comment]
Left my thoughts [here](https://discord.com/channels/1163352113162768436/1163352113859002400/1167556431537516657) , but basically I think having perma killing as a threat is good for the game, having it happen is good for RP, and it’ll be rare enough alongside respawning providing options for players so that adding a way to outright undo rot isn’t all that interesting imho.

Increasing the rot timer to 15-20 minutes is probably fine, though.
