### ISSUE TITLE
Lost and Found Locker Creates New Entities

### ISSUE THREAD

**Issue by Nairodian** [cosmatic-drift-14/cosmatic-drift#443]
## Description
Bit of a 'holy shit' issue. The cryosleep system copies, deletes, then pastes _prototypes_/entities.

This causes all containers to be reset to their default contents, meaning all things in backpacks are deleted, secbelts are magically restored, and guns get their mag back.

This also causes things to be insanely hard to keep track of in admin logs, as they are now new entities with new EntIDs.

**Reproduction**
Put something unique in a container > Enter cryosleep > Check Lost and Found.

**Screenshots**
https://www.youtube.com/watch?v=cJTPTEm-8hg

**Additional context**
N/A

**Comment by dffdff2423** [comment]
This explains so much.
