### ISSUE TITLE
Lost and Found Should Be a UI

### ISSUE THREAD

**Issue by Nairodian** [cosmatic-drift-14/cosmatic-drift#444]
## Description
Building off of #367 to fully explain it.

The Lost and Found Locker should remade into a "Lost and Found Storage Unit" or like, "Cryosleep Item Storage." Then from there it should have a very similar UI to that of Upstream's (see image for reference), where each person who has entered cryo is listed with their name and probably their job as their own tab, and from there the user can remove selected items one by one.

So the real difference is just take Upstream's system, and make it centralized to one location in the HoP's office.

![image](https://github.com/user-attachments/assets/f25429b8-0ab6-4aa7-9d54-e80fe7f69900)

**Comment by dffdff2423** [comment]
Cryosleep should return the same exact item to make forensics possible. This would also eliminate a class of issues like bags not copying their contents.

**Comment by dffdff2423** [comment]
See also: #457
